apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray-hello-world
spec:
  selector:
    matchLabels:
      app: v2ray-hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: v2ray-hello-world
    spec:
      containers:
      - name: v2ray-hello-world
        image: okteto.dev/zizifn-hello-world:latest
        resources:
         limits:
           memory: 512Mi
           cpu: "1"
        env:
        - name: PORT
          value: "8888"
        - name: UUID
          value: "48f2d803-5f4e-40ae-b400-2c0ff9d74d0c"
        ports:
        - containerPort: 8888